### ISSUE TITLE
评论无法正常使用

### ISSUE THREAD

**Issue by kands-code** [random-yang/paper#33]
我按照要求配置好主题后，评论是出来了，可是点提交没反应，是因为在手机移动端的缘故吗？

这个是我的博客，不信的话可以尝试一下。

https://qarks.top

**Comment by random-yang** [comment]
好的，找到问题后给你反馈。

**Comment by random-yang** [comment]
在你的blog控制台抛出了错误：
<img width="264" alt="image" src="https://user-images.githubusercontent.com/25839518/81035162-5e9c5e00-8ecc-11ea-9ac2-3569fee00201.png">

但是我在我目前的master版本下测试是没有这个报错的。

你可以检查一下你的`themes/paper/_config.yml`文件中的`comment`是否配置正确(尤其是检查appid这一项)。还有就是我不确定你是否修改了`paper/layout/includes/comments-script.pug`下面的东西。

正确的应该是大概长这样：

```
comment:
  enable: true
  appId: 1JY5EfxxxxaiEGxxxxrCs7dk-gzGxxxxz
  appKey: jXutXUNavOPDp9eyrtshfkoi
  placeholder: say something
  notify: false
  verify: false
  avatar: mp
```
